In [3]:
!pip install matplotlib

In [3]:

import numpy as np
#tạo mảng
a = np.array([1,2,3])
#in mảng
print(a)

#in ra 1 phần tử
element = a[1]
print(element)

[1 2 3]
2


In [5]:
#tạo mảng 2 chiều 
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(3)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(8)
print(a)

# Tạo mảng
a = np.empty(3)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(95)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [11]:
#thêm, xóa, sắp xếp mảng
arr = np.array([2, 5 ,3, 4, 1,6 ,7 ,8])
print(arr)
#sắp xếp
arr = np.sort(arr)
print(arr)
# Sắp xếp ngược
arr = np.sort(arr)[::-1]
print(arr)
#thêm phần tử vào mảng
arr = np.append(arr, 20)
print(arr)
#xóa đi một ví trí nào đó trong mảng
arr = np.delete(arr, 5)
print(arr)

[2 5 3 4 1 6 7 8]
[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
[ 8  7  6  5  4  3  2  1 20]
[ 8  7  6  5  4  2  1 20]


In [13]:
#tạo một mảng 2 chiều
arr = np.array([[4, 5, 6],
                [3, 1, 2],
                [7, 9, 8]])

sap_xep_theo_hang = np.sort(arr, axis=1) #tăng 
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) #tăng 
print(sap_xep_theo_cot)

[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[3 1 2]
 [4 5 6]
 [7 9 8]]


In [15]:
#tạo một mảng 2 chiều
arr = np.array([[4, 5, 6],
                [3, 1, 2],
                [7, 9, 8]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giảm 
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # giảm
print(sap_xep_theo_cot)

[[6 5 4]
 [3 2 1]
 [9 8 7]]
[[7 9 8]
 [4 5 6]
 [3 1 2]]


In [17]:
#tạo mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

#sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # số chiều (2 chiều)
kich_thuoc = arr.size  # kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # hình dạng (số hàng x số cột, (2, 3))

print("số chiều:", so_chieu)
print("kích thước:", kich_thuoc)
print("hình dạng:", hinh_dang)

số chiều: 2
kích thước: 6
hình dạng: (2, 3)


In [19]:
#chuyển đổi kiểu dữ liệu
arr = np.array([4, 5, 6, 7, 8])
arr_float = arr.astype(float)
print(arr_float)

[4. 5. 6. 7. 8.]


In [21]:
#thay đổi hình dạng của mảng
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [23]:
reshaped_arr = reshaped_arr.flatten() #chuyển sang mảng 1 chiều
print(reshaped_arr)

[1 2 3 4 5 6]


In [27]:
#cát mảng
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  #cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  #1 2 3 4
print(sub_arr)

sub_arr = arr[-2:]  #4 5 
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [29]:
#chuyển vị trí mảng
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
#để chuyển vị trí mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [31]:
#nối mảng
arr1 = np.array([2, 3, 4])
arr2 = np.array([5, 6, 7])
arr = np.concatenate((arr1, arr2))
print(arr)

[2 3 4 5 6 7]
